# Generated by Django 5.2.14 on 2026-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
    ]
